/* config.h.  Generated by configure.  */
/* config-in.h.  Generated automatically from configure.in by autoheader.  */
/* version number */
#define BUILDVER_STRING "4.8.02 (0030)"

/* define if intptr_t and uintptr_t are defined. */
#define  _INTPTR_T_DEFINED 1
#define _UINTPTR_T_DEFINED 1

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define to 'int' if <sys/types.h> doesn't define. */
/* #undef socklen_t */

/* Define to 'unsigned long' if <sys/types.h> doesn't define. */
/* #undef ulong */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if you want privlege separation enabled. */
#define USE_PRIVSEP 1

/* Define if your <sys/time.h> declares struct tm.  */
/* #undef TM_IN_SYS_TIME */

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #undef WORDS_BIGENDIAN */

/* #undef STRICT_ALIGNMENT */

/* Define if you have the itoa function.  */
/* #undef HAVE_ITOA */

/* Define if you have the ftime function. */
#define HAVE_FTIME 1

/* Define if you have the <arpa/inet.h> header file.  */
#define HAVE_ARPA_INET_H 1

/* Define if you have the <dirent.h> header file.  */
#define HAVE_DIRENT_H 1

/* Define if you have the <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1

/* Define if you have the <inttypes.h> header file.  */
#define HAVE_INTTYPES_H 1

/* Define if you have the <limits.h> header file.  */
#define HAVE_LIMITS_H 1

/* Define if you have the <malloc.h> header file.  */
#define HAVE_MALLOC_H 1

/* Define if you have the <ndir.h> header file.  */
/* #undef HAVE_NDIR_H */

/* Define if you have the <netdb.h> header file.  */
#define HAVE_NETDB_H 1

/* Define if you have the <netinet/in.h> header file.  */
#define HAVE_NETINET_IN_H 1

/* Define if you have the <stdint.h> header file.  */
#define HAVE_STDINT_H 1

/* Define if you have the <stdlib.h> header file.  */
#define HAVE_STDLIB_H 1

/* Define if you have the <sys/dir.h> header file.  */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/ioctl.h> header file.  */
#define HAVE_SYS_IOCTL_H 1

/* Define if you have the <sys/ndir.h> header file.  */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/param.h> header file.  */
#define HAVE_SYS_PARAM_H 1

/* Define if you have the <sys/socket.h> header file.  */
#define HAVE_SYS_SOCKET_H 1

/* Define if you have the <sys/sockio.h> header file.  */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <sys/types.h> header file.  */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <sys/utsname.h> header file.  */
#define HAVE_SYS_UTSNAME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <paths.h> header file.  */
#define HAVE_PATHS_H 1

/* access rights in msghdr */
/* #undef HAVE_ACCRIGHTS_IN_MSGHDR */

/* ancillary data style fd pass */
#define HAVE_CONTROL_IN_MSGHDR 1

/* sendmsg function. */
#define HAVE_SENDMSG 1

/* recvmsg function. */
#define HAVE_RECVMSG 1

/* socketpair streamed pipe. */
#define HAVE_SOCKETPAIR 1

/* Name of package */
#define PACKAGE "cisco-vpnclient"

/* Version number of package */
#define VERSION "4.8.02"

/* platform definition for rsa libraries see bsfplatf.h */
#define RSA_PLATFORM RSA_LINUX

/* obsolete location of config files. can only be changed at compile time. */
#define OLD_CONFIG_PATH "/etc/CiscoSystemsVPNClient"

/* location of config file. can only be changed at compile time. */
#define UNITY_CONFIG_PATH "/etc/opt/cisco-vpnclient"

/* location of executables. can also be changed in vpnclient.ini */
#define UNITY_DEFAULT_BINDIR "/opt/cisco-vpnclient/bin"

/* name of the dotfile directory where we can put config. */
#define UNITY_HOMEDIR_PATH ".cisco-vpnclient"

/* defines to facilitate separate builds for solaris 2.6 and 2.8 */

#define PLATFORM_LINUX 1
/* #undef PLATFORM_SOLARIS */
/* #undef PLATFORM_DARWIN */
/* #undef PLATFORM_DARWIN_8 */

#define IFR_MTU ifr_mtu
#define PORTABLE_SIOCGIFCONF SIOCGIFCONF

/* use ioctl() polling instead of generated packets for ipcs from the driver */
#define DRIVER_IPC_VIA_IOCTL 1

/* Enable Virtual Adapter */
#define VIRTUAL_ADAPTER 1
